from constants import *

CHARACTERS = [
    {"name": "Brawler", "color": RED,    "speed": 4, "jump": -14,
     "punch_dmg": 12, "kick_dmg": 18, "max_hp": 130, "block": 6,
     "desc": "Tanky heavy hitter",   "double_jump": False},
    {"name": "Ninja",   "color": CYAN,   "speed": 7, "jump": -16,
     "punch_dmg":  7, "kick_dmg": 10, "max_hp":  90, "block": 8,
     "desc": "Fast & double jump",   "double_jump": True},
    {"name": "Boxer",   "color": GREEN,  "speed": 5, "jump": -13,
     "punch_dmg": 16, "kick_dmg":  8, "max_hp": 110, "block": 9,
     "desc": "Devastating punches",  "double_jump": False},
    {"name": "Phantom", "color": PURPLE, "speed": 6, "jump": -15,
     "punch_dmg": 10, "kick_dmg": 14, "max_hp": 100, "block": 7,
     "desc": "Balanced & evasive",   "double_jump": True},
    {"name": "Ares",    "color": ORANGE, "speed": 5,  "jump": -14,
     "punch_dmg": 21, "kick_dmg": 20, "max_hp": 90, "block": 3,
     "desc": "God of War",           "double_jump": False},
    {"name": "Zephyr",  "color": BLUE,  "speed": 9,  "jump": -18,
     "punch_dmg": 10, "kick_dmg": 14, "max_hp": 100, "block": 7,
     "desc": "Swift and agile",      "double_jump": True},
    {"name": "Titan",  "color": YELLOW,  "speed": 3,  "jump": -7,
     "punch_dmg": 18, "kick_dmg": 16, "max_hp": 155, "block": 3,
     "desc": "Enormous Health",      "double_jump": False},
    {"name": "Dancing Man",    "color": (100, 100, 255), "speed": 10,  "jump": -20,
     "punch_dmg": 10, "kick_dmg": 10, "max_hp": 100, "block": 6,
     "desc": "evasive",    "double_jump": True},
    {"name": "Tank",   "color": (30, 30, 30), "speed": 1,  "jump": -0,
     "punch_dmg": 10, "kick_dmg": 12, "max_hp": 190, "block": 9,
     "desc": "Defensive",   "double_jump": False},
    {"name": "Mighty Medieval Man",  "color": GRAY, "speed": 4,  "jump": -18,
     "punch_dmg": 15, "kick_dmg": 15, "max_hp": 120, "block": 8,
     "desc": "Lord of chivalry",   "double_jump": False},
    {"name": "Samurai",   "color": BLACK, "speed": 6,  "jump": -15,
     "punch_dmg": 12, "kick_dmg": 19, "max_hp": 170, "block": 7,
     "desc": "Katana Master",   "double_jump": True},
    {"name": "Skeleton",   "color": WHITE,   "speed": 3, "jump": -5,
     "punch_dmg":  25, "kick_dmg": 20, "max_hp":  65, "block": 2,
     "desc": "Dead",   "double_jump": False},
    {"name": "Unknown",   "color": (100, 160, 220),   "speed": 5,  "jump": -5,
     "punch_dmg":  3, "kick_dmg": 5, "max_hp":  300, "block": 5,
     "desc": "Mysterious and powerful",   "double_jump": True},
    {"name": "Hardy", "color": (110, 120, 225), "speed": 3, "jump": -5,
     "punch_dmg": 3, "kick_dmg": 4, "max_hp": 65, "block": 2,
     "desc": "Pros should try him",   "double_jump": False},
    {"name": "Rogue", "color": (220, 180, 60), "speed": 8, "jump": -17,
     "punch_dmg": 10, "kick_dmg": 12, "max_hp": 80, "block": 6,
     "desc": "Stealthy and agile",   "double_jump": True},
    {"name": "Gladiator", "color": (200, 80, 80), "speed": 4, "jump": -12,
     "punch_dmg": 14, "kick_dmg": 18, "max_hp": 140, "block": 7,
     "desc": "Arena Champion",   "double_jump": False},
    {"name": "Oni", "color": (80, 220, 200), "speed": 2, "jump": -1,
     "punch_dmg": 12, "kick_dmg": 14, "max_hp": 200, "block": 3,
     "desc": "Fat Demon",   "double_jump": False},
    {"name": "Cecalia",     "color": (50, 255, 255), "speed": 8,  "jump": -8,
     "punch_dmg": 8,  "kick_dmg": 8,  "max_hp": 300, "block": 4,
     "desc": "Octo hard",        "double_jump": False},
    {"name": "Acrobat",     "color": (255, 180, 80), "speed": 8,  "jump": -20,
     "punch_dmg": 8,  "kick_dmg": 12, "max_hp": 85, "block": 6,
     "desc": "Aerial specialist", "double_jump": True},
    {"name": "Shapeshifter", "color": (180, 80, 255), "speed": 6, "jump": -15,
     "punch_dmg": 14, "kick_dmg": 14, "max_hp": 105, "block": 5,
     "desc": "Unpredictable",    "double_jump": True},
    {"name": "Spring",   "color": (255, 100, 100), "speed": 10, "jump": -45,
     "punch_dmg": 1, "kick_dmg": 1, "max_hp": 400, "block": 1,
     "desc": "Bouncy",   "double_jump": True},
    {"name": "Harpy",   "color": (150, 0, 150), "speed": 9, "jump": -19,
     "punch_dmg": 20, "kick_dmg": 20, "max_hp": 40, "block": 3,
     "desc": "Blood-eater",   "double_jump": True},
    {"name": "Scarecrow",   "color": (50, 0, 50), "speed": 1, "jump": -0,
     "punch_dmg": 100, "kick_dmg": 100, "max_hp": 60, "block": 1,
     "desc": "Strong and Weak",   "double_jump": False},
    {"name": "Cactus", "color": (40, 180, 60), "speed": 4, "jump": -11,
     "punch_dmg": 4, "kick_dmg": 4, "max_hp": 135, "block": 4,
     "desc": "Poisons on contact", "double_jump": False, "contact_dmg": 8},
    {"name": "Medic", "color": (200, 255, 200), "speed": 5, "jump": -13,
     "punch_dmg": 7, "kick_dmg": 9, "max_hp": 120, "block": 6,
     "desc": "+2 HP every 5 seconds", "double_jump": False, "regen": True},
    {"name": "Arsonist", "color": (255, 80, 20), "speed": 6, "jump": -14,
     "punch_dmg": 10, "kick_dmg": 8, "max_hp": 100, "block": 4,
     "desc": "Punches set targets on fire", "double_jump": False, "fire_punch": True},
    {"name": "Cryogenisist", "color": (150, 220, 255), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 0, "max_hp": 110, "block": 6,
     "desc": "Kicks freeze opponents for 3s", "double_jump": False, "freeze_kick": True},
    {"name": "Magician", "color": (180, 80, 255), "speed": 5, "jump": -13,
     "punch_dmg": 8, "kick_dmg": 10, "max_hp": 105, "block": 7,
     "desc": "Powerups drift toward him", "double_jump": True, "magnet": True},
    {"name": "Charger", "color": (255, 220, 0), "speed": 5, "jump": -13,
     "punch_dmg": 7, "kick_dmg": 9, "max_hp": 115, "block": 5,
     "desc": "Punches shock: halves speed for 8 sec", "double_jump": False, "shock_punch": True},
    {"name": "Psychopath", "color": (180, 0, 180), "speed": 6, "jump": -14,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 100, "block": 2,
     "desc": "Kick teleports to random spot", "double_jump": False, "teleport_kick": True},
    {"name": "Ran-Doom", "color": (128, 128, 128), "speed": 5, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 10, "max_hp": 110, "block": 5,
     "desc": "All stats randomized each match", "double_jump": False, "random_stats": True},
    {"name": "Outbacker", "color": (200, 130, 50), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 7, "max_hp": 115, "block": 5,
     "desc": "Kick throws orbiting boomerang", "double_jump": False, "boomerang_kick": True},
    {"name": "Gunner", "color": (60, 180, 80), "speed": 5, "jump": -13,
     "punch_dmg": 8, "kick_dmg": 0, "max_hp": 110, "block": 4,
     "desc": "Kicks shoot a ball (10 dmg)", "double_jump": False, "shoot_kick": True},
    {"name": "Bazooka Man", "color": (180, 60, 60), "speed": 1, "jump": -0,
     "punch_dmg": 8, "kick_dmg": 0, "max_hp": 75, "block": 1,
     "desc": "Kick fires exploding orb (35 dmg)", "double_jump": False, "bazooka_kick": True},
    {"name": "Pinball", "color": (255, 80, 200), "speed": 5, "jump": -13,
     "punch_dmg": 8, "kick_dmg": 0, "max_hp": 110, "block": 5,
     "desc": "Kick shoots a bouncing ball (10 dmg)", "double_jump": False, "bounce_kick": True},
    {"name": "Giant", "color": (100, 160, 100), "speed": 2, "jump": -8,
     "punch_dmg": 20, "kick_dmg": 18, "max_hp": 260, "block": 4,
     "desc": "Very big and very strong", "double_jump": False, "giant": True},
    {"name": "Morph", "color": (80, 200, 220), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 110, "block": 5,
     "desc": "Kick cycles size: normal → big → small", "double_jump": False, "size_kick": True},
    {"name": "Ghost", "color": (210, 210, 255), "speed": 5, "jump": -15,
     "punch_dmg": 8, "kick_dmg": 9, "max_hp": 105, "block": 8,
     "desc": "Floats freely — hold jump to rise, duck to sink", "double_jump": True,
     "phase": True, "ghost_float": True},
    {"name": "Vampire", "color": (120, 0, 40), "speed": 6, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 90, "block": 5,
     "desc": "Heals 8 HP on every hit", "double_jump": False, "vampire": True},
    {"name": "Astronaut", "color": (220, 230, 255), "speed": 5, "jump": -10,
     "punch_dmg": 8, "kick_dmg": 9, "max_hp": 105, "block": 5,
     "desc": "Anti-gravity on every map", "double_jump": True, "anti_gravity": True},
    {"name": "Spooderman", "color": (180, 20, 20), "speed": 7, "jump": -16,
     "punch_dmg": 10, "kick_dmg": 12, "max_hp": 100, "block": 7,
     "desc": "Clings to walls, wall-jumps", "double_jump": True, "wall_cling": True},
    {"name": "Hooker", "color": (40, 160, 60), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 0, "max_hp": 110, "block": 5,
     "desc": "Kick fires a snake grappling hook", "double_jump": False, "grapple_kick": True},
    {"name": "Mouse", "color": (200, 180, 160), "speed": 9, "jump": -17,
     "punch_dmg": 6, "kick_dmg": 8, "max_hp": 65, "block": 8,
     "desc": "Tiny and very hard to hit", "double_jump": True, "tiny": True},
    {"name": "Sumo", "color": (255, 200, 100), "speed": 1, "jump": -2,
     "punch_dmg": 1, "kick_dmg": 1, "max_hp": 600, "block": 10,
     "desc": "Enormous health, barely moves", "double_jump": False},
    {"name": "Headless Horseman", "color": (80, 40, 15), "speed": 7, "jump": -11,
     "punch_dmg": 13, "kick_dmg": 0, "max_hp": 145, "block": 5,
     "desc": "Kicks throw a physics pumpkin that explodes", "double_jump": False, "pumpkin_kick": True},
    {"name": "Ink Brush", "color": (20, 20, 40), "speed": 6, "jump": -14,
     "punch_dmg": 10, "kick_dmg": 12, "max_hp": 110, "block": 6,
     "desc": "Kick spawns a moving clone that distracts enemies", "double_jump": True, "ink_kick": True},
    {"name": "Hammerhead", "color": (80, 55, 30), "speed": 3, "jump": -11,
     "punch_dmg": 22, "kick_dmg": 6, "max_hp": 135, "block": 5,
     "desc": "Hammer punch squishes opponents flat for 4 seconds", "double_jump": False, "hammer_punch": True},
    {"name": "Viking", "color": (180, 130, 60), "speed": 4, "jump": -13,
     "punch_dmg": 15, "kick_dmg": 13, "max_hp": 145, "block": 5,
     "desc": "Goes berserk below 50% HP: speed & damage x1.5", "double_jump": False, "berserker": True},
    {"name": "Wizard", "color": (100, 60, 200), "speed": 5, "jump": -14,
     "punch_dmg": 11, "kick_dmg": 8, "max_hp": 95, "block": 6,
     "desc": "Punch fires a bouncing magic orb", "double_jump": True, "bounce_punch": True},
    {"name": "Wrestler", "color": (220, 100, 40), "speed": 3, "jump": -10,
     "punch_dmg": 12, "kick_dmg": 8, "max_hp": 155, "block": 6,
     "desc": "Kick sends opponents flying across the arena", "double_jump": False, "slam_kick": True},
    {"name": "Clown", "color": (255, 60, 120), "speed": 7, "jump": -15,
     "punch_dmg": 8, "kick_dmg": 10, "max_hp": 100, "block": 4,
     "desc": "Kick reverses opponent controls for 3 seconds", "double_jump": True, "confuse_kick": True},
    {"name": "Speedster", "color": (255, 200, 0), "speed": 13, "jump": -17,
     "punch_dmg": 7, "kick_dmg": 9, "max_hp": 85, "block": 5,
     "desc": "Blazing fast with a speed trail", "double_jump": True, "speedster": True},
    {"name": "Knight", "color": (160, 160, 180), "speed": 3, "jump": -11,
     "punch_dmg": 17, "kick_dmg": 15, "max_hp": 150, "block": 12,
     "desc": "Heavily armored — massive block rating", "double_jump": False},
    {"name": "Lava Man",   "color": (230, 80, 20),   "speed": 4, "jump": -13,
     "punch_dmg": 11, "kick_dmg": 9,  "max_hp": 115, "block": 4,
     "desc": "Burns on contact; punches ignite foes", "double_jump": False,
     "fire_punch": True, "contact_dmg": 10},
    {"name": "Angel",      "color": (255, 250, 210),  "speed": 6, "jump": -18,
     "punch_dmg": 8,  "kick_dmg": 10, "max_hp": 90,  "block": 6,
     "desc": "Slow fall — glides gracefully in the air", "double_jump": True, "slow_fall": True},
    {"name": "Mime",       "color": (240, 240, 240),  "speed": 6, "jump": -14,
     "punch_dmg": 10, "kick_dmg": 8,  "max_hp": 100, "block": 7,
     "desc": "Landing a punch turns Mime invisible for 2s", "double_jump": False, "stealth_punch": True},
    {"name": "Lumberjack", "color": (160, 80, 30),    "speed": 4, "jump": -12,
     "punch_dmg": 14, "kick_dmg": 11, "max_hp": 140, "block": 5,
     "desc": "Axe swing hits at double reach", "double_jump": False, "wide_punch": True},
    {"name": "Bouncer",    "color": (80, 200, 80),    "speed": 4, "jump": -12,
     "punch_dmg": 10, "kick_dmg": 12, "max_hp": 130, "block": 8,
     "desc": "Reflects 50% damage back when blocking", "double_jump": False, "reflect_block": True},
    {"name": "Demon",      "color": (160, 20, 20),    "speed": 7, "jump": -15,
     "punch_dmg": 16, "kick_dmg": 14, "max_hp": 110, "block": 4,
     "desc": "Dark and powerful demon warrior", "double_jump": True},
    {"name": "Dark Mage",  "color": (60, 20, 100),    "speed": 5, "jump": -14,
     "punch_dmg": 10, "kick_dmg": 8,  "max_hp": 100, "block": 6,
     "desc": "Magic orb punch + freeze kick combo", "double_jump": True,
     "bounce_punch": True, "freeze_kick": True},
    {"name": "Pirate",     "color": (80, 55, 30),     "speed": 4, "jump": -12,
     "punch_dmg": 10, "kick_dmg": 0,  "max_hp": 120, "block": 5,
     "desc": "Fires an explosive cannonball on kick (35 dmg)", "double_jump": False, "bazooka_kick": True},
    {"name": "Elemental", "color": (120, 200, 255), "speed": 6, "jump": -14,
     "punch_dmg": 8, "kick_dmg": 8, "max_hp": 25, "block": 5,
     "desc": "Every ability — only 25 HP",
     "double_jump": True,
     # Punch abilities
     "fire_punch": True, "shock_punch": True, "hammer_punch": True,
     "wide_punch": True, "bounce_punch": True, "stealth_punch": True,
     # Kick abilities — ALL fire at once
     "shoot_kick": True, "bounce_kick": True, "boomerang_kick": True,
     "bazooka_kick": True, "pumpkin_kick": True, "grapple_kick": True,
     "ink_kick": True, "confuse_kick": True, "teleport_kick": True,
     "slam_kick": True, "freeze_kick": True,
     # Passives
     "vampire": True, "regen": True, "berserker": True,
     "contact_dmg": 5, "reflect_block": True, "magnet": True,
     "speedster": True, "phase": True, "wall_cling": True,
     "slow_fall": True, "laser_eyes": True},
    {"name": "Impossible", "color": CYAN,    "speed": 10, "jump": -16,
     "punch_dmg": 1, "kick_dmg": 1, "max_hp": 1, "block": 1,
     "desc": "gods at this game should try him",   "double_jump": True},
    {"name": "Laser Eyes", "color": (255, 60, 0), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 105, "block": 5,
     "desc": "Every 10s fires a laser beam for 2s", "double_jump": False, "laser_eyes": True},
    {"name": "Whipper", "color": (160, 90, 20), "speed": 5, "jump": -13,
     "punch_dmg": 3, "kick_dmg": 12, "max_hp": 110, "block": 6,
     "desc": "Long-range whip punch — 280px reach, 14 damage", "double_jump": False, "whip_punch": True},
    {"name": "Mr. Crit", "color": (255, 200, 0), "speed": 5, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 11, "max_hp": 100, "block": 5,
     "desc": "Every punch is a critical hit (+10 dmg)", "double_jump": False, "always_crit": True},
    {"name": "Chameleon", "color": (60, 180, 80), "speed": 6, "jump": -14,
     "punch_dmg": 9, "kick_dmg": 11, "max_hp": 105, "block": 6,
     "desc": "Blends into the background — nearly invisible", "double_jump": False, "chameleon": True},
    {"name": "omuS", "color": WHITE, "speed": 8, "jump": -14,
     "punch_dmg": 700, "kick_dmg": 700, "max_hp": 1, "block": 0,
     "desc": "Don't you recognize him?",   "double_jump": True},
    {"name": "Kitsune", "color": (255, 130, 0), "speed": 7, "jump": -14,
     "punch_dmg": 8, "kick_dmg": 9, "max_hp": 110, "block": 5,
     "desc": "Every 9s fires 9 projectiles in 9 directions (9 dmg each)", "double_jump": True,
     "kitsune_barrage": True},
    {"name": "Medusa", "color": (80, 200, 80), "speed": 5, "jump": -12,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 120, "block": 6,
     "desc": "Every 10s fires a gaze beam that freezes for 3s", "double_jump": False,
     "freeze_laser": True},
    {"name": "The Creator", "color": (200, 155, 50), "speed": 6, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 10, "max_hp": 130, "block": 5,
     "desc": "Kick creates a platform obstacle", "double_jump": True,
     "creator_kick": True},
    {"name": "Disorientated", "color": (180, 90, 200), "speed": 7, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 10, "max_hp": 120, "block": 5,
     "desc": "All controls reversed: W=S, A=D, punch=kick and vice versa", "double_jump": True,
     "disorientated": True},
    {"name": "Janitor", "color": (210, 210, 180), "speed": 5, "jump": -11,
     "punch_dmg": 8, "kick_dmg": 8, "max_hp": 160, "block": 7,
     "desc": "Completely immune to all special effects", "double_jump": False,
     "immune": True},
    {"name": "Riptide", "color": (0, 180, 230), "speed": 7, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 9, "max_hp": 120, "block": 5,
     "desc": "Kick fires a wavy water ball (12 dmg)", "double_jump": True,
     "water_kick": True},
    {"name": "Whirlpool", "color": (0, 140, 200), "speed": 5, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 12, "max_hp": 115, "block": 5,
     "desc": "Builds speed the longer he keeps running (up to 2.5x)", "double_jump": False,
     "momentum": True},
    {"name": "Shadowfax", "color": (215, 215, 240), "speed": 9, "jump": -14,
     "punch_dmg": 9, "kick_dmg": 11, "max_hp": 110, "block": 5,
     "desc": "Leaves a smoke trail wherever he runs", "double_jump": True,
     "smoke_trail": True},
    {"name": "ASCII", "color": (0, 255, 120), "speed": 7, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 10, "max_hp": 120, "block": 6,
     "desc": "Made entirely of keyboard keys", "double_jump": True,
     "ascii_fighter": True},
    # ---------- new batch ----------
    {"name": "Snake", "color": (20, 200, 60), "speed": 4, "jump": -10,
     "punch_dmg": 8, "kick_dmg": 10, "max_hp": 100, "block": 5,
     "desc": "Slithers freely — body grows on powerups & deals contact damage",
     "double_jump": False, "snake": True, "phase": True},
    {"name": "Enraged", "color": (220, 40, 20), "speed": 10, "jump": -15,
     "punch_dmg": 20, "kick_dmg": 20, "max_hp": 28, "block": 2,
     "desc": "Permanently in berserk mode — insane power, almost no health",
     "double_jump": True, "always_berserk": True},
    {"name": "Beekeeper", "color": (220, 180, 0), "speed": 5, "jump": -13,
     "punch_dmg": 6, "kick_dmg": 9, "max_hp": 110, "block": 5,
     "desc": "Punch unleashes a swarm of 5 bees (5 dmg each)", "double_jump": False,
     "bee_punch": True},
    {"name": "Plague Doctor", "color": (80, 180, 80), "speed": 4, "jump": -12,
     "punch_dmg": 9, "kick_dmg": 8, "max_hp": 120, "block": 6,
     "desc": "Punches apply fire + poison + shock simultaneously", "double_jump": False,
     "plague_punch": True},
    {"name": "Necromancer", "color": (80, 40, 140), "speed": 4, "jump": -12,
     "punch_dmg": 10, "kick_dmg": 12, "max_hp": 90, "block": 5,
     "desc": "Revives once at 40% HP when first killed", "double_jump": True,
     "undead": True},
    {"name": "Joker", "color": (200, 60, 255), "speed": 7, "jump": -14,
     "punch_dmg": 8, "kick_dmg": 9, "max_hp": 100, "block": 4,
     "desc": "Every 12s randomly applies freeze/fire/shock/confuse to opponent",
     "double_jump": True, "chaos_timer": True},
    {"name": "Blitzer", "color": (255, 160, 0), "speed": 6, "jump": -14,
     "punch_dmg": 7, "kick_dmg": 9, "max_hp": 95, "block": 5,
     "desc": "Punches have almost no cooldown — rapid-fire brawler", "double_jump": False,
     "rapid_fire": True},
    {"name": "Vamp Lord", "color": (100, 0, 40), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 100, "block": 5,
     "desc": "Kick drains 20 HP from opponent to self", "double_jump": False,
     "drain_kick": True},
    {"name": "Iron Fist", "color": (180, 180, 200), "speed": 3, "jump": -11,
     "punch_dmg": 18, "kick_dmg": 8, "max_hp": 140, "block": 6,
     "desc": "Punches deal triple knockback and extend stagger", "double_jump": False,
     "iron_fist": True},
    {"name": "Toxic", "color": (60, 220, 60), "speed": 4, "jump": -12,
     "punch_dmg": 7, "kick_dmg": 9, "max_hp": 115, "block": 5,
     "desc": "Passive aura poisons anyone nearby", "double_jump": False,
     "toxic_aura": True},
    {"name": "Time Lord", "color": (100, 180, 255), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 11, "max_hp": 110, "block": 5,
     "desc": "Every 18s freezes opponent for 4 seconds", "double_jump": True,
     "time_freeze": True},
    {"name": "Shifter", "color": (160, 120, 255), "speed": 6, "jump": -14,
     "punch_dmg": 11, "kick_dmg": 10, "max_hp": 110, "block": 5,
     "desc": "Attacks cycle each punch: Normal → Whip → Snipe → repeat",
     "double_jump": True, "cycle_attack": True},
    {"name": "Kamikaze", "color": (255, 100, 0), "speed": 8, "jump": -15,
     "punch_dmg": 12, "kick_dmg": 14, "max_hp": 65, "block": 3,
     "desc": "Explodes on death dealing 60 AoE damage to nearby opponent",
     "double_jump": True, "explode_death": True},
    {"name": "Shrink Ray", "color": (120, 255, 200), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 8, "max_hp": 110, "block": 5,
     "desc": "Kick shrinks opponent to tiny size for 5 seconds",
     "double_jump": False, "shrink_kick": True},
    {"name": "Levitator", "color": (200, 160, 255), "speed": 5, "jump": -15,
     "punch_dmg": 9, "kick_dmg": 11, "max_hp": 105, "block": 5,
     "desc": "Kick launches opponent straight up into the air",
     "double_jump": True, "launch_kick": True},
    {"name": "Stalker", "color": (60, 80, 60), "speed": 7, "jump": -14,
     "punch_dmg": 10, "kick_dmg": 11, "max_hp": 100, "block": 4,
     "desc": "Every hit permanently steals 8% speed from the opponent",
     "double_jump": True, "speed_steal": True},
    {"name": "Mirror Man", "color": (200, 220, 240), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 115, "block": 8,
     "desc": "Reflects projectiles back at the shooter while blocking",
     "double_jump": False, "reflect_proj": True},
    {"name": "Pyro", "color": (255, 80, 0), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 110, "block": 4,
     "desc": "Auto-fires a burning fireball at opponent every 5 seconds",
     "double_jump": False, "auto_fire": True},
    {"name": "Thunder God", "color": (255, 240, 80), "speed": 4, "jump": -12,
     "punch_dmg": 14, "kick_dmg": 10, "max_hp": 130, "block": 5,
     "desc": "Punch drops a lightning bolt from above onto the opponent",
     "double_jump": False, "thunder_punch": True},
    {"name": "Glass Cannon", "color": (200, 240, 255), "speed": 7, "jump": -15,
     "punch_dmg": 30, "kick_dmg": 28, "max_hp": 15, "block": 1,
     "desc": "Devastating damage — but only 15 HP",
     "double_jump": True, "glass_cannon": True},
    {"name": "Teleporter", "color": (80, 200, 220), "speed": 6, "jump": -14,
     "punch_dmg": 10, "kick_dmg": 11, "max_hp": 105, "block": 5,
     "desc": "Automatically teleports to a random position every 8 seconds",
     "double_jump": True, "auto_teleport": True},
    {"name": "Sticker", "color": (200, 180, 60), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 110, "block": 5,
     "desc": "Punch roots opponent in place for 2 seconds",
     "double_jump": False, "sticky_punch": True},
    # ── new batch ────────────────────────────────────────────────────────────
    {"name": "Gargoyle", "color": (120, 110, 130), "speed": 1, "jump": -0,
     "punch_dmg": 10, "kick_dmg": 8, "max_hp": 200, "block": 15,
     "desc": "Stone guardian — reflects ALL blocked damage back at attacker",
     "double_jump": False, "reflect_block": True},
    {"name": "Banshee", "color": (210, 140, 255), "speed": 7, "jump": -16,
     "punch_dmg": 11, "kick_dmg": 8, "max_hp": 75, "block": 4,
     "desc": "Floats through floors — punch ignites foes",
     "double_jump": True, "ghost_float": True, "phase": True, "fire_punch": True},
    {"name": "Storm Caller", "color": (80, 120, 255), "speed": 5, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 9, "max_hp": 110, "block": 5,
     "desc": "Punch drops a lightning bolt at a random location",
     "double_jump": False, "storm_punch": True},
    {"name": "Magnetar", "color": (160, 80, 255), "speed": 5, "jump": -12,
     "punch_dmg": 10, "kick_dmg": 9, "max_hp": 115, "block": 5,
     "desc": "Punch yanks the opponent 100px closer",
     "double_jump": False, "magnet_punch": True},
    {"name": "Swamp Thing", "color": (40, 100, 30), "speed": 2, "jump": -5,
     "punch_dmg": 8, "kick_dmg": 10, "max_hp": 180, "block": 6,
     "desc": "Toxic aura poisons all nearby AND deals contact damage",
     "double_jump": False, "toxic_aura": True, "contact_dmg": 6},
    {"name": "Duelist", "color": (220, 180, 40), "speed": 6, "jump": -14,
     "punch_dmg": 11, "kick_dmg": 10, "max_hp": 100, "block": 5,
     "desc": "Cycling attacks: Normal → Whip → Snipe — goes invisible on punch hit",
     "double_jump": True, "cycle_attack": True, "stealth_punch": True},
    {"name": "Polar Bear", "color": (230, 240, 255), "speed": 2, "jump": -8,
     "punch_dmg": 14, "kick_dmg": 0, "max_hp": 200, "block": 7,
     "desc": "Wide icy punch + freeze kick — slow but enormous and deadly",
     "double_jump": False, "wide_punch": True, "freeze_kick": True},
    {"name": "Quaker", "color": (160, 120, 60), "speed": 4, "jump": -15,
     "punch_dmg": 10, "kick_dmg": 12, "max_hp": 125, "block": 5,
     "desc": "Landing from height creates a 15-damage shockwave in 140px radius",
     "double_jump": False, "quake_land": True},
    {"name": "Echo", "color": (80, 200, 180), "speed": 6, "jump": -13,
     "punch_dmg": 8, "kick_dmg": 9, "max_hp": 105, "block": 5,
     "desc": "Consecutive punches within 1.5s build +5 bonus damage each hit",
     "double_jump": True, "combo_punch": True},
    {"name": "Phantom Thief", "color": (60, 60, 100), "speed": 7, "jump": -15,
     "punch_dmg": 9, "kick_dmg": 11, "max_hp": 95, "block": 6,
     "desc": "Kick steals one active powerup from the opponent",
     "double_jump": True, "steal_kick": True},
    {"name": "Cloned", "color": (100, 200, 160), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 90, "block": 4,
     "desc": "Starts every fight with a permanent infinite-HP AI clone of itself",
     "double_jump": False, "cloned": True},
    {"name": "Bomb", "color": (200, 80, 20), "speed": 6, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 110, "block": 4,
     "desc": "Every 5 seconds a bomb spawns at center-screen — explodes for 100 dmg to everyone",
     "double_jump": False, "bomb_character": True},
    {"name": "Halves", "color": (220, 80, 220), "speed": 5, "jump": -14,
     "punch_dmg": 5, "kick_dmg": 12, "max_hp": 100, "block": 5,
     "desc": "Punch removes exactly half of the opponent's current HP",
     "double_jump": True, "halves_punch": True},
    {"name": "Godslayer", "color": (180, 20, 60), "speed": 6, "jump": -14,
     "punch_dmg": 18, "kick_dmg": 16, "max_hp": 85, "block": 4,
     "desc": "When HP drops below 30%, next attack deals 999 damage — once per life",
     "double_jump": True, "godslayer": True},
    {"name": "Scrollmaster", "color": (180, 150, 80), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 100, "block": 4,
     "desc": "Kick shoots a scroll that bounces everywhere and grows every second",
     "double_jump": False, "scroll_kick": True},
    {"name": "Boulder", "color": (120, 90, 60), "speed": 2, "jump": -10,
     "punch_dmg": 22, "kick_dmg": 18, "max_hp": 200, "block": 9,
     "desc": "Incredibly slow but impossibly tanky — punch sends opponents flying",
     "double_jump": False, "iron_fist": True},
    {"name": "Wisp", "color": (180, 240, 255), "speed": 11, "jump": -16,
     "punch_dmg": 5, "kick_dmg": 6, "max_hp": 60, "block": 2,
     "desc": "Lightning fast, feather light — floats and double jumps everywhere",
     "double_jump": True, "slow_fall": True},
    {"name": "Sandman", "color": (220, 190, 120), "speed": 4, "jump": -12,
     "punch_dmg": 9, "kick_dmg": 8, "max_hp": 95, "block": 4,
     "desc": "Punch puts the opponent to sleep for 1.5 seconds",
     "double_jump": False, "sleep_punch": True},
    {"name": "Reaper", "color": (40, 40, 40), "speed": 7, "jump": -14,
     "punch_dmg": 10, "kick_dmg": 13, "max_hp": 80, "block": 3,
     "desc": "Kick instantly kills anyone at 20% HP or below",
     "double_jump": True, "reaper_kick": True},
    {"name": "Chainsaw Man", "color": (200, 60, 30), "speed": 4, "jump": -11,
     "punch_dmg": 8, "kick_dmg": 7, "max_hp": 115, "block": 4,
     "desc": "Deals rapid contact damage to anyone standing close",
     "double_jump": False, "chainsaw": True},
    {"name": "Crusher", "color": (140, 80, 200), "speed": 4, "jump": -12,
     "punch_dmg": 16, "kick_dmg": 14, "max_hp": 110, "block": 5,
     "desc": "Punches break through any block — blocking does nothing against him",
     "double_jump": False, "crush_punch": True},
    {"name": "Storm Witch", "color": (160, 80, 220), "speed": 5, "jump": -13,
     "punch_dmg": 8, "kick_dmg": 10, "max_hp": 90, "block": 4,
     "desc": "Punch calls random lightning; kick freezes the opponent",
     "double_jump": True, "storm_punch": True, "freeze_kick": True},
    {"name": "Blood Baron", "color": (160, 0, 40), "speed": 5, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 12, "max_hp": 85, "block": 4,
     "desc": "Kick steals HP; fire punch burns the opponent",
     "double_jump": False, "drain_kick": True, "fire_punch": True},
    {"name": "Drifter", "color": (100, 180, 160), "speed": 7, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 90, "block": 4,
     "desc": "Phases through all platforms — gravity is just a suggestion",
     "double_jump": False, "phase": True},
    {"name": "Warlock", "color": (80, 40, 160), "speed": 5, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 10, "max_hp": 95, "block": 5,
     "desc": "Punch drops targeted lightning; kick scrambles the opponent's controls",
     "double_jump": True, "thunder_punch": True, "confuse_kick": True},
    {"name": "Flash", "color": (255, 200, 0), "speed": 9, "jump": -14,
     "punch_dmg": 9, "kick_dmg": 9, "max_hp": 85, "block": 3,
     "desc": "Kick teleports him instantly behind the opponent",
     "double_jump": True, "flash_kick": True},
    {"name": "Portal Maker", "color": (80, 200, 255), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 95, "block": 4,
     "desc": "Kicks create 2 linked portals — step in one, come out the other",
     "double_jump": False, "portal_kick": True},
    {"name": "Gravity", "color": (120, 80, 200), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 11, "max_hp": 90, "block": 4,
     "desc": "Kick drops 20 apples from above — each one deals damage",
     "double_jump": False, "apple_kick": True},
    {"name": "Swapper", "color": (200, 120, 60), "speed": 6, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 95, "block": 5,
     "desc": "Kick instantly swaps positions with the opponent",
     "double_jump": True, "swap_kick": True},
    {"name": "Bruiser", "color": (180, 60, 60), "speed": 4, "jump": -12,
     "punch_dmg": 12, "kick_dmg": 10, "max_hp": 120, "block": 5,
     "desc": "Gets angrier each hit taken — punch power grows with every hurt",
     "double_jump": False, "rage_build": True},
    {"name": "Grappler", "color": (80, 140, 200), "speed": 4, "jump": -11,
     "punch_dmg": 14, "kick_dmg": 10, "max_hp": 130, "block": 6,
     "desc": "Punch yanks the opponent right in front of you — point blank every time",
     "double_jump": False, "grab_punch": True},
    {"name": "Trickster", "color": (200, 80, 200), "speed": 7, "jump": -14,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 90, "block": 4,
     "desc": "Punch reverses the opponent's controls for 2 seconds",
     "double_jump": True, "confuse_punch": True},
    {"name": "Wildcard", "color": (255, 180, 0), "speed": 6, "jump": -13,
     "punch_dmg": 5, "kick_dmg": 5, "max_hp": 100, "block": 4,
     "desc": "Every attack deals a completely random amount of damage (1–40)",
     "double_jump": False, "wild_attack": True},
    {"name": "Ironclad", "color": (150, 150, 170), "speed": 3, "jump": -11,
     "punch_dmg": 13, "kick_dmg": 11, "max_hp": 160, "block": 7,
     "desc": "Passive armor — takes 40% less damage from every hit",
     "double_jump": False, "stone_skin": True},
    {"name": "Siphon", "color": (160, 40, 160), "speed": 5, "jump": -13,
     "punch_dmg": 8, "kick_dmg": 9, "max_hp": 90, "block": 4,
     "desc": "Every hit — punch or kick — drains 10 HP from the opponent to self",
     "double_jump": True, "siphon_leech": True},
    {"name": "Timekeeper", "color": (100, 200, 240), "speed": 5, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 9, "max_hp": 105, "block": 5,
     "desc": "Punch slows the opponent to half speed for 6 seconds",
     "double_jump": False, "slow_punch": True},
    {"name": "Rainbow Man", "color": (255, 100, 180), "speed": 6, "jump": -14,
     "punch_dmg": 8, "kick_dmg": 9, "max_hp": 100, "block": 4,
     "desc": "Poops out random powerups every 4 seconds — for everyone",
     "double_jump": True, "rainbow_poop": True},
    {"name": "Spitting Cobra", "color": (60, 180, 40), "speed": 7, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 9, "max_hp": 95, "block": 4,
     "desc": "Kick spits a venom bean — deals damage and poisons the opponent",
     "double_jump": False, "venom_kick": True},
    {"name": "Pacman", "color": (255, 220, 0), "speed": 6, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 10, "max_hp": 100, "block": 5,
     "desc": "Chomps enemies on contact — deals 50 damage and grows bigger",
     "double_jump": False, "chomp": True},
    # ── Secret characters ────────────────────────────────────────────────────
    {"name": "777", "color": (255, 215, 0), "speed": 5, "jump": -13,
     "punch_dmg": 8, "kick_dmg": 9, "max_hp": 100, "block": 4,
     "desc": "Every 7 punches you land, the 7th deals +7 bonus damage",
     "double_jump": False, "seven_punch": True},
    {"name": "Scratch", "color": (160, 160, 160), "speed": 5, "jump": -13,
     "punch_dmg": 8, "kick_dmg": 9, "max_hp": 100, "block": 4,
     "desc": "Just a normal stickman. Nothing special.",
     "double_jump": False},
    {"name": "Void Master", "color": (30, 0, 60), "speed": 6, "jump": -14,
     "punch_dmg": 10, "kick_dmg": 12, "max_hp": 95, "block": 5,
     "desc": "Cannot die by falling into the void",
     "double_jump": True, "void_immune": True},
    {"name": "Screentime", "color": (100, 200, 255), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 100, "block": 4,
     "desc": "Distorts time — slows 1v1 to half speed, doubles survival speed",
     "double_jump": False, "screentime": True},
    {"name": "God", "color": (255, 255, 200), "speed": 7, "jump": -15,
     "punch_dmg": 14, "kick_dmg": 12, "max_hp": 120, "block": 6,
     "desc": "Thunder punch, flame punch, shock kick, and poison aura — all at once",
     "double_jump": True,
     "thunder_punch": True, "fire_punch": True, "shock_kick": True, "toxic_aura": True},
    {"name": "Nightfall", "color": (20, 0, 60), "speed": 6, "jump": -14,
     "punch_dmg": 13, "kick_dmg": 11, "max_hp": 90, "block": 5,
     "desc": "Punch drains the opponent's life — steals 15 HP per hit",
     "double_jump": True, "drain_punch": True},
    {"name": "Lucky", "color": (255, 215, 0), "speed": 5, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 10, "max_hp": 100, "block": 4,
     "desc": "Every attack has a 25% chance to deal triple damage — pure chaos",
     "double_jump": False, "lucky_strike": True},
    {"name": "Great Totem Spirit", "color": (190, 110, 30), "speed": 5, "jump": -13,
     "punch_dmg": 11, "kick_dmg": 12, "max_hp": 105, "block": 5,
     "desc": "Kick summons 5 totem poles that crash down from above",
     "double_jump": False, "totem_kick": True},
    {"name": "Prime Time", "color": (60, 180, 255), "speed": 6, "jump": -13,
     "punch_dmg": 2, "kick_dmg": 2, "max_hp": 100, "block": 4,
     "desc": "Each attack deals the next prime number: 2, 3, 5, 7, 11, 13...",
     "double_jump": False, "prime_dmg": True},
    {"name": "Rage Quitter", "color": (220, 40, 0), "speed": 7, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 8, "max_hp": 90, "block": 3,
     "desc": "Kick fires an explosive remote controller — 100 damage on contact",
     "double_jump": True, "remote_kick": True},
    {"name": "The One", "color": (230, 220, 255), "speed": 7, "jump": -15,
     "punch_dmg": 13, "kick_dmg": 13, "max_hp": 110, "block": 6,
     "desc": "Has it all — fire punch, thunder, drain kick, leech, berserk, lucky & more",
     "double_jump": True,
     "vampire": True, "regen": True, "berserker": True,
     "fire_punch": True, "thunder_punch": True,
     "shock_kick": True, "freeze_kick": True, "drain_kick": True,
     "iron_fist": True, "lucky_strike": True},
    {"name": "Mirror", "color": (180, 230, 255), "speed": 5, "jump": -13,
     "punch_dmg": 1, "kick_dmg": 10, "max_hp": 105, "block": 5,
     "desc": "Punch copies the opponent's punch stat — fights fire with fire",
     "double_jump": False, "copy_punch": True},
    {"name": "Paradox", "color": (80, 40, 200), "speed": 5, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 12, "max_hp": 100, "block": 5,
     "desc": "First punch swaps both fighters' HP — use it at the right moment",
     "double_jump": True, "hp_swap": True},
    {"name": "Jetpack", "color": (200, 100, 255), "speed": 6, "jump": -16,
     "punch_dmg": 10, "kick_dmg": 11, "max_hp": 95, "block": 4,
     "desc": "Unlimited jumps + slow fall — floats anywhere he pleases",
     "double_jump": True, "slow_fall": True, "jetpack": True},
    {"name": "The Impossible Victor", "color": (0, 255, 180), "speed": 8, "jump": -15,
     "punch_dmg": 700, "kick_dmg": 700, "max_hp": 2, "block": 0,
     "desc": "Born from Impossible — hits like a truck, dies from a sneeze",
     "double_jump": True},
    {"name": "ChickenBanana", "color": (255, 200, 0), "speed": 6, "jump": -13,
     "punch_dmg": 11, "kick_dmg": 11, "max_hp": 100, "block": 5,
     "desc": "Automatically rams in facing direction every 8 seconds — instant kill on contact, wall = 10 self dmg",
     "double_jump": False, "chicken_banana": True},
    {"name": "Soul Master", "color": (80, 0, 160), "speed": 6, "jump": -14,
     "punch_dmg": 10, "kick_dmg": 12, "max_hp": 110, "block": 6,
     "desc": "Every 5 seconds his soul jumps to a new clone — sudden teleport across the stage",
     "double_jump": True, "ink_kick": True, "soul_master": True},
    {"name": "Scorpio", "color": (160, 70, 10), "speed": 5, "jump": -13,
     "punch_dmg": 12, "kick_dmg": 10, "max_hp": 105, "block": 5,
     "desc": "Half scorpion — kicks freeze AND poison for 3s", "double_jump": False, "scorpio_kick": True},
    {"name": "Nuke", "color": (40, 40, 40), "speed": 4, "jump": -12,
     "punch_dmg": 10, "kick_dmg": 10, "max_hp": 110, "block": 4,
     "desc": "Every 5s a 200-damage bomb spawns at center-screen", "double_jump": False,
     "bomb_character": True, "nuke_bomb": True},
    {"name": "Druid", "color": (30, 120, 30), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 11, "max_hp": 110, "block": 6,
     "desc": "Kick sprouts a plant spike from the ground at opponent", "double_jump": False, "plant_kick": True},
    {"name": "Big Bad Critter Clad", "color": (75, 50, 25), "speed": 3, "jump": -11,
     "punch_dmg": 15, "kick_dmg": 13, "max_hp": 250, "block": 8,
     "desc": "Armored beast — only critical hits deal real damage", "double_jump": False, "crit_only": True},
    {"name": "Dementor", "color": (20, 10, 40), "speed": 5, "jump": -14,
     "punch_dmg": 10, "kick_dmg": 12, "max_hp": 100, "block": 5,
     "desc": "Restores to full HP every 20 seconds", "double_jump": True, "dementor_heal": True},
    {"name": "Life the Universe Everything", "color": (0, 180, 200), "speed": 6, "jump": -14,
     "punch_dmg": 42, "kick_dmg": 42, "max_hp": 100, "block": 6,
     "desc": "The answer. 42 damage every hit.", "double_jump": False},
    # ── new batch ────────────────────────────────────────────────────────────
    {"name": "Shade", "color": (25, 25, 45), "speed": 7, "jump": -15,
     "punch_dmg": 11, "kick_dmg": 12, "max_hp": 85, "block": 5,
     "desc": "Always invisible — only flickers visible while attacking",
     "double_jump": True, "shade": True},
    {"name": "Decay", "color": (75, 55, 30), "speed": 4, "jump": -12,
     "punch_dmg": 10, "kick_dmg": 10, "max_hp": 115, "block": 5,
     "desc": "Each punch permanently reduces opponent's max HP by 8",
     "double_jump": False, "decay_punch": True},
    {"name": "Fault Line", "color": (150, 100, 50), "speed": 5, "jump": -13,
     "punch_dmg": 9, "kick_dmg": 11, "max_hp": 110, "block": 5,
     "desc": "Punch sends a shockwave rolling across the ground (15 dmg)",
     "double_jump": False, "quake_punch": True},
    {"name": "Buckler", "color": (70, 160, 100), "speed": 4, "jump": -12,
     "punch_dmg": 10, "kick_dmg": 10, "max_hp": 130, "block": 6,
     "desc": "Blocking heals 6 HP instead of reducing damage",
     "double_jump": False, "absorb_block": True},
    {"name": "Overdrive", "color": (255, 130, 0), "speed": 6, "jump": -14,
     "punch_dmg": 10, "kick_dmg": 10, "max_hp": 100, "block": 4,
     "desc": "Every 4 hits received charges him — next attack deals 3x damage",
     "double_jump": False, "overdrive": True},
    {"name": "Hypnotist", "color": (140, 60, 200), "speed": 6, "jump": -14,
     "punch_dmg": 9, "kick_dmg": 11, "max_hp": 100, "block": 5,
     "desc": "Kick hypnotizes opponent — forces them to walk toward Hypnotist for 2s",
     "double_jump": True, "hypno_kick": True},
    {"name": "Revenant", "color": (160, 90, 200), "speed": 5, "jump": -13,
     "punch_dmg": 10, "kick_dmg": 12, "max_hp": 80, "block": 4,
     "desc": "Revives up to 2 times at 30% HP when killed",
     "double_jump": True, "revenant": True},
    {"name": "Volt", "color": (220, 240, 60), "speed": 7, "jump": -14,
     "punch_dmg": 9, "kick_dmg": 10, "max_hp": 95, "block": 4,
     "desc": "Every 3s automatically shocks opponent if within 140px (8 dmg)",
     "double_jump": False, "shock_aura": True},
    {"name": "Phantom Strike", "color": (50, 50, 160), "speed": 6, "jump": -14,
     "punch_dmg": 12, "kick_dmg": 10, "max_hp": 90, "block": 4,
     "desc": "Teleports adjacent to opponent before each punch lands",
     "double_jump": True, "phantom_strike": True},
    {"name": "Trap Master", "color": (110, 85, 40), "speed": 4, "jump": -12,
     "punch_dmg": 9, "kick_dmg": 8, "max_hp": 120, "block": 5,
     "desc": "Kick plants a ground mine at your feet — explodes for 25 dmg when stepped on",
     "double_jump": False, "mine_kick": True},
    {"name": "Juggernaut", "color": (180, 60, 20), "speed": 2, "jump": -9,
     "punch_dmg": 18, "kick_dmg": 16, "max_hp": 200, "block": 5,
     "desc": "Cannot be knocked back — hits deal damage but never move him",
     "double_jump": False, "juggernaut": True},
    {"name": "Mirage", "color": (160, 210, 230), "speed": 7, "jump": -15,
     "punch_dmg": 8, "kick_dmg": 9, "max_hp": 75, "block": 3,
     "desc": "35% chance to phase-dodge any incoming attack",
     "double_jump": True, "mirage": True},
]

POWERUPS = [
    # --- existing ---
    {'name': 'Swiftness',     'type': 'speed',     'mult': 1.6,  'duration': 360, 'color': (80, 200, 250)},
    {'name': 'Rage',      'type': 'kick_dmg',  'amount': 10, 'duration': 500, 'color': (240,120,  40)},
    {'name': 'Drugs',     'type': 'punch_dmg', 'amount': 10, 'duration': 540, 'color': (180,240, 180)},
    {'name': 'Heal',      'type': 'heal',       'amount': 30, 'duration': 0,   'color': (200,255, 120)},
    {'name': 'Poison',    'type': 'heal',       'amount':-30, 'duration': 0,   'color': (200,160, 255)},
    # --- new ---
    {'name': 'Turbo',     'type': 'speed',     'mult': 2.4,  'duration': 180, 'color': (255,230,   0)},
    {'name': 'Forcefield',    'type': 'shield',    'reduction': 0.5, 'duration': 360, 'color': (100,150, 255)},
    {'name': 'Leech',     'type': 'leech',     'amount':  8, 'duration': 360, 'color': (200,  0, 200)},
    {'name': 'MegaHeal',  'type': 'heal',      'amount': 60, 'duration': 0,   'color': (0,   220,  80)},
    {'name': 'Killer',      'type': 'heal',      'amount':-60, 'duration': 0,   'color': (255,  60,   0)},
    {'name': 'Wither',      'type': 'speed',     'amount':  -2, 'duration': 420, 'color': (255,  0,  0)},
    {'name': '2x Trouble',  'type': 'clone',     'duration': 0,                  'color': (255, 80, 200)},
    {'name': 'Cleanse',       'type': 'cleanse',       'duration': 0,        'color': (205, 205, 155)},
    {'name': 'Bubble Shield', 'type': 'bubble_shield', 'duration': FPS * 10, 'color': (100, 200, 255)},
    {'name': 'Everything',    'type': 'poop',          'duration': FPS * 10, 'color': (255, 255, 255)},
]

STAGES = [
    # Grasslands
    {"name": "Grasslands", "platforms": [
        (60,  GROUND_Y-90,  200, 0,   0),
        (640, GROUND_Y-140, 140, 0,   0),
        (310, GROUND_Y-215, 210, 1.5, 140),
    ], "springs": [
        (310, -22), (620, -22),
    ], "conveyors": [
        (50,  GROUND_Y, 180, 2.5),
        (650, GROUND_Y, 180, -2.5),
    ], "portals": [(160, GROUND_Y-160), (700, GROUND_Y-160)]},
    # Volcano
    {"name": "Volcano", "platforms": [
        (70,  GROUND_Y-120, 130, 2,   80),
        (630, GROUND_Y-150, 120, -2,  70),
        (395, GROUND_Y-240, 100, 0,   0),
    ], "springs": [
        (450, -30),
    ], "conveyors": [
        (80,  GROUND_Y, 200, 3.5),
        (600, GROUND_Y, 200, -3.5),
    ], "portals": [(140, GROUND_Y-180), (710, GROUND_Y-180)]},
    # Dojo
    {"name": "Dojo", "platforms": [
        (50,  GROUND_Y-115, 155, 0,   0),
        (695, GROUND_Y-115, 155, 0,   0),
        (355, GROUND_Y-205, 145, 2.5, 100),
    ], "springs": [
        (230, -22), (670, -22),
    ], "conveyors": [
        (200, GROUND_Y, 200, -2.0),
        (500, GROUND_Y, 200,  2.0),
    ], "portals": [(130, GROUND_Y-170), (730, GROUND_Y-170)]},
    # Desert
    {"name": "Desert", "platforms": [
        (80,  GROUND_Y-75,  220, 0,   0),
        (590, GROUND_Y-110, 190, 0,   0),
        (330, GROUND_Y-185, 180, 1,   160),
    ], "springs": [
        (180, -20), (450, -20), (720, -20),
    ], "conveyors": [
        (50,  GROUND_Y, 260, 1.8),
        (570, GROUND_Y, 260, -1.8),
    ], "portals": [(150, GROUND_Y-140), (700, GROUND_Y-140)]},
    # Arena
    {"name": "Arena", "platforms": [
        (80,  GROUND_Y-110, 140, 2,   120),
        (620, GROUND_Y-110, 140, -2,  120),
        (350, GROUND_Y-210, 160, 3,   160),
    ], "springs": [
        (250, -24), (640, -24),
    ], "conveyors": [
        (50,  GROUND_Y, 350, 3.0),
        (500, GROUND_Y, 350, -3.0),
    ], "portals": [(160, GROUND_Y-175), (690, GROUND_Y-175)]},
    # Dream Land
    {"name": "Dream Land", "platforms": [
        (55,  GROUND_Y-95,  175, 0,   0),
        (670, GROUND_Y-95,  175, 0,   0),
        (195, GROUND_Y-190, 155, 0,   0),
        (550, GROUND_Y-190, 155, 0,   0),
    ], "springs": [
        (80,  -22), (235, -22), (390, -22),
        (530, -22), (680, -22), (820, -22),
    ], "conveyors": [
        (60,  GROUND_Y, 160, 1.5),
        (680, GROUND_Y, 160, -1.5),
    ], "portals": [(120, GROUND_Y-150), (740, GROUND_Y-150)]},
    # Underworld
    {"name": "Underworld", "platforms": [
        (55,  GROUND_Y-105, 165, 0,   0),
        (680, GROUND_Y-105, 165, 0,   0),
        (270, GROUND_Y-175, 135, 1.5, 110),
        (495, GROUND_Y-175, 135, -1.5,110),
    ], "springs": [
        (200, -22), (450, -22), (700, -22),
    ], "conveyors": [
        (50,  GROUND_Y, 220, -2.5),
        (620, GROUND_Y, 220,  2.5),
    ], "portals": [(170, GROUND_Y-165), (690, GROUND_Y-165)]},
    # Space
    {"name": "Space", "platforms": [
        (80,  GROUND_Y-120, 150, 1.5, 110),
        (630, GROUND_Y-120, 150, -1.5,110),
        (355, GROUND_Y-230, 130, 2.5, 100),
    ], "springs": [
        (280, -26), (620, -26),
    ], "conveyors": [
        (60,  GROUND_Y, 200, 2.0),
        (640, GROUND_Y, 200, -2.0),
    ], "portals": [(155, GROUND_Y-190), (710, GROUND_Y-190)]},
    # Jungle
    {"name": "Jungle", "platforms": [
        (55,  GROUND_Y-110, 175, 0,   0),
        (670, GROUND_Y-110, 175, 0,   0),
        (340, GROUND_Y-210, 150, 1.2, 120),
    ], "springs": [
        (450, -22),
    ], "conveyors": [
        (50,  GROUND_Y, 240, 2.2),
        (600, GROUND_Y, 240, -2.2),
    ], "portals": [(140, GROUND_Y-160), (720, GROUND_Y-160)]},
    # Computer
    {"name": "Computer", "platforms": [
        (60,  GROUND_Y-105, 160, 0,   0),
        (680, GROUND_Y-105, 160, 0,   0),
        (330, GROUND_Y-200, 140, 1.5, 120),
    ], "springs": [], "conveyors": [
        (50,  GROUND_Y, 200, 2.8),
        (640, GROUND_Y, 200, -2.8),
    ], "portals": [(160, GROUND_Y-170), (700, GROUND_Y-170)]},
    # Ice Cave
    {"name": "Ice Cave", "platforms": [
        (50,  GROUND_Y-100, 180, 0,   0),
        (670, GROUND_Y-130, 160, 0,   0),
        (340, GROUND_Y-220, 160, 2.0, 130),
    ], "springs": [
        (200, -22), (700, -22),
    ], "conveyors": [
        (50,  GROUND_Y, 300, 4.5),
        (550, GROUND_Y, 300, -4.5),
    ], "portals": [(140, GROUND_Y-165), (720, GROUND_Y-165)]},
    # Pirate Ship
    {"name": "Pirate Ship", "platforms": [
        (55,  GROUND_Y-90,  170, 1.0, 110),
        (670, GROUND_Y-120, 155, -1.0,110),
        (350, GROUND_Y-205, 140, 0,   0),
    ], "springs": [
        (430, -22),
    ], "conveyors": [
        (60,  GROUND_Y, 220, 2.0),
        (610, GROUND_Y, 220, -2.0),
    ], "portals": [(150, GROUND_Y-155), (710, GROUND_Y-155)]},
    # City Rooftop
    {"name": "City Rooftop", "platforms": [
        (60,  GROUND_Y-130, 150, 0,   0),
        (690, GROUND_Y-100, 140, 0,   0),
        (365, GROUND_Y-215, 130, 1.8, 100),
        (170, GROUND_Y-215, 120, 0,   0),
    ], "springs": [
        (250, -22), (650, -22),
    ], "conveyors": [
        (80,  GROUND_Y, 180, 2.5),
        (630, GROUND_Y, 180, -2.5),
    ], "portals": [(160, GROUND_Y-180), (700, GROUND_Y-145)]},
    # Medieval Castle
    {"name": "Medieval Castle", "platforms": [
        (55,  GROUND_Y-110, 165, 0,   0),
        (680, GROUND_Y-110, 165, 0,   0),
        (310, GROUND_Y-200, 145, 1.5, 120),
        (460, GROUND_Y-285, 110, 0,   0),
    ], "springs": [
        (350, -22), (600, -22),
    ], "conveyors": [
        (70,  GROUND_Y, 200, 1.8),
        (620, GROUND_Y, 200, -1.8),
    ], "portals": [(145, GROUND_Y-170), (715, GROUND_Y-170)]},
    # Circus
    {"name": "Circus", "platforms": [
        (60,  GROUND_Y-100, 160, 2.0, 130),
        (670, GROUND_Y-140, 150, -2.0,130),
        (345, GROUND_Y-220, 170, 0,   0),
    ], "springs": [
        (200, -22), (450, -22), (720, -22),
    ], "conveyors": [
        (55,  GROUND_Y, 240, 3.0),
        (590, GROUND_Y, 240, -3.0),
    ], "portals": [(165, GROUND_Y-175), (695, GROUND_Y-175)]},
    # The Void
    {"name": "The Void", "platforms": [
        (310, GROUND_Y-70,  280, 0,   0),    # large central platform (spawn zone)
        (50,  GROUND_Y-160, 175, 0,   0),    # left ledge
        (675, GROUND_Y-160, 175, 0,   0),    # right ledge
        (175, GROUND_Y-270, 140, 1.8, 110),  # left floating
        (580, GROUND_Y-270, 140, -1.8,110),  # right floating
        (380, GROUND_Y-360, 120, 0,   0),    # top centre
    ], "springs": [
        (430, -22), (580, -22),
    ], "conveyors": [], "portals": [(160, GROUND_Y-230), (700, GROUND_Y-230)]},
    # Underwater
    {"name": "Underwater", "platforms": [
        (60,  GROUND_Y-95,  175, 0.8, 100),
        (660, GROUND_Y-130, 165, -0.8,100),
        (330, GROUND_Y-210, 150, 1.2, 120),
    ], "springs": [
        (300, -22), (600, -22),
    ], "conveyors": [
        (60,  GROUND_Y, 210, 1.5),
        (620, GROUND_Y, 210, -1.5),
    ], "portals": [(155, GROUND_Y-160), (705, GROUND_Y-185)]},
    # Arctic Tundra
    {"name": "Arctic Tundra", "platforms": [
        (55,  GROUND_Y-100, 180, 0,   0),
        (665, GROUND_Y-130, 160, 0,   0),
        (335, GROUND_Y-220, 160, 0,   0),
    ], "springs": [
        (220, -22), (680, -22),
    ], "conveyors": [
        (50,  GROUND_Y, 320, 5.0),
        (530, GROUND_Y, 320, -5.0),
    ], "portals": [(145, GROUND_Y-165), (720, GROUND_Y-165)]},
    # Haunted House
    {"name": "Haunted House", "platforms": [
        (60,  GROUND_Y-110, 160, 0,   0),
        (680, GROUND_Y-110, 160, 0,   0),
        (320, GROUND_Y-215, 150, 1.2, 110),
        (150, GROUND_Y-300, 120, 0,   0),
    ], "springs": [
        (390, -22),
    ], "conveyors": [
        (60,  GROUND_Y, 200, -1.8),
        (640, GROUND_Y, 200,  1.8),
    ], "portals": [(155, GROUND_Y-175), (710, GROUND_Y-175)]},
    # Volcano Core
    {"name": "Volcano Core", "platforms": [
        (55,  GROUND_Y-90,  170, 1.5, 100),
        (675, GROUND_Y-120, 155, -1.5,100),
        (360, GROUND_Y-200, 135, 0,   0),
        (200, GROUND_Y-295, 110, 2.0, 90),
        (590, GROUND_Y-295, 110, -2.0,90),
    ], "springs": [
        (440, -22),
    ], "conveyors": [
        (60,  GROUND_Y, 220, 3.2),
        (620, GROUND_Y, 220, -3.2),
    ], "portals": [(160, GROUND_Y-210), (700, GROUND_Y-210)]},
    # Sky Island
    {"name": "Sky Island", "platforms": [
        (80,  GROUND_Y-150, 160, 0,   0),
        (660, GROUND_Y-150, 160, 0,   0),
        (350, GROUND_Y-255, 145, 0,   0),
        (200, GROUND_Y-340, 110, 0,   0),
        (590, GROUND_Y-340, 110, 0,   0),
    ], "springs": [
        (160, -22), (460, -22), (740, -22),
    ], "conveyors": [
        (80,  GROUND_Y, 180, 1.5),
        (640, GROUND_Y, 180, -1.5),
    ], "portals": [(165, GROUND_Y-210), (695, GROUND_Y-210)]},
    # Graveyard
    {"name": "Graveyard", "platforms": [
        (50,  GROUND_Y-105, 170, 0,   0),
        (680, GROUND_Y-130, 155, 0,   0),
        (330, GROUND_Y-210, 145, 1.0, 100),
        (460, GROUND_Y-295, 115, 0,   0),
    ], "springs": [
        (300, -22), (620, -22),
    ], "conveyors": [
        (55,  GROUND_Y, 210, -2.0),
        (635, GROUND_Y, 210,  2.0),
    ], "portals": [(150, GROUND_Y-165), (715, GROUND_Y-165)]},
    # The Nether
    {"name": "The Nether", "platforms": [
        (80,  GROUND_Y-120, 180, 0,   0),
        (640, GROUND_Y-120, 180, 0,   0),
        (340, GROUND_Y-210, 160, 0,   0),
    ], "springs": [], "conveyors": [], "portals": [(175, GROUND_Y-180), (700, GROUND_Y-180)]},
]

# Stage-specific character advantages and disadvantages.
# adv gets +25% speed & +25% damage; dis gets -20% speed & -20% damage.
STAGE_MATCHUPS = {
    "Grasslands": {"adv": "Scarecrow",   "dis": "Titan"},
    "Volcano":    {"adv": "Arsonist",    "dis": "Cryogenisist"},
    "Dojo":       {"adv": "Ninja",       "dis": "Oni"},
    "Desert":     {"adv": "Cactus",      "dis": "Tank"},
    "Arena":      {"adv": "Gladiator",   "dis": "Rogue"},
    "Dream Land": {"adv": "Spring",      "dis": "Brawler"},
    "Underworld": {"adv": "Skeleton",    "dis": "Boxer"},
    "Space":      {"adv": "Astronaut",    "dis": "Giant"},
    "Jungle":     {"adv": "Hooker",       "dis": "Gunner"},
    "Computer":        {"adv": "Charger",      "dis": "Viking"},
    "Ice Cave":        {"adv": "Cryogenisist", "dis": "Arsonist"},
    "Pirate Ship":     {"adv": "Pirate",        "dis": "Wizard"},
    "City Rooftop":    {"adv": "Speedster",     "dis": "Headless Horseman"},
    "Medieval Castle": {"adv": "Knight",        "dis": "Vampire"},
    "Circus":          {"adv": "Clown",         "dis": "Samurai"},
    "Underwater":      {"adv": "Cecalia",       "dis": "Arsonist"},
    "The Void":        {"adv": "Acrobat",       "dis": "Titan"},
    "Arctic Tundra":   {"adv": "Cryogenisist",  "dis": "Lava Man"},
    "Haunted House":   {"adv": "Ghost",          "dis": "Rogue"},
    "Volcano Core":    {"adv": "Lava Man",       "dis": "Cryogenisist"},
    "Sky Island":      {"adv": "Angel",          "dis": "Sumo"},
    "Graveyard":       {"adv": "Ghost",       "dis": "Medic"},
    "The Nether":      {"adv": "Void Master", "dis": "Wisp"},
}

